
version: "3.1"
services:

    mysql:
      image: mysql:5.7
      container_name: recruit-delivery-cost-mysql
      working_dir: /app
      volumes:
        - .:/app
        - ./data/:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=database
        - MYSQL_USER=user
        - MYSQL_PASSWORD=password
      ports:
        - "8052:3306"

    webserver:
      image: nginx:alpine
      container_name: recruit-delivery-cost-webserver
      working_dir: /var/www
      volumes:
          - ./app:/var/www
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
          - ./logs:/var/log/nginx/
      ports:
       - "8050:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: recruit-delivery-cost-php-fpm
      working_dir: /var/www
      volumes:
        - ./app:/var/www
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini

